export enum CarBrand {
    MarutiSuzuki = "Maruti Suzuki",
    Hyundai = "Hyundai",
    Tata = "Tata",
    Mahindra = "Mahindra",
    Honda = "Honda",
    Toyota = "Toyota",
    Ford = "Ford",
    Volkswagen = "Volkswagen",
    Nissan = "Nissan",
    Renault = "Renault",
    Kia = "Kia",
    Skoda = "Skoda",
    MG = "MG",
    Jeep = "Jeep",
    BMW = "BMW",
    MercedesBenz = "Mercedes-Benz",
    Audi = "Audi",
    Jaguar = "Jaguar",
    Volvo = "Volvo",
    Porsche = "Porsche",
    LandRover = "Land Rover",
}
